[package]
name = "hover"
version = "0.0.0"
edition = "2021"

[dependencies]
text-size = "1.1.1"

base_db.workspace = true
schema_cache.workspace = true
tracing.workspace = true

[dev-dependencies]

[lib]
doctest = false

[features]
