[workspace]
members = [
    "crates/*",
]

[workspace.dependencies]
parser = { path = "./crates/parser", version = "0.0.0" }
codegen = { path = "./crates/codegen", version = "0.0.0" }
sourcegen = { path = "./crates/sourcegen", version = "0.0.0" }
pg_query_proto_parser = { path = "./crates/pg_query_proto_parser", version = "0.0.0" }
triomphe = { version = "0.1.8", default-features = false, features = ["std"] }


