[package]
name = "lint"
version = "0.0.0"
edition = "2021"

[dependencies]
base_db.workspace = true
schema_cache.workspace = true
tracing.workspace = true

[dev-dependencies]

[lib]
doctest = false

[features]
