[package]
name = "typecheck_sqlx"
version = "0.0.0"
edition = "2021"

[dependencies]
base_db.workspace = true
schema_cache.workspace = true
text-size = "1.1.1"
sql_parser.workspace = true
async-std = "1.12.0"
tracing.workspace = true
sqlx = { version = "0.7.3", features = [ "runtime-async-std", "tls-rustls", "postgres", "json" ] }

[dev-dependencies]

[lib]
doctest = false

[features]
