[package]
name = "pg_syntax"
version = "0.0.0"
edition = "2021"

[dependencies]
petgraph = "0.6.4"

cstree = { version = "0.12.0", features = ["derive"] }
text-size = "1.1.1"

pg_query_ext.workspace = true
pg_lexer.workspace = true


