[package]
name = "pg_schema_cache"
version = "0.0.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0" }
serde = "1.0.195"
serde_json = "1.0.114"

sqlx.workspace = true

[lib]
doctest = false
