[package]
name = "pg_schema_cache"
version = "0.0.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0" }
serde.workspace = true
serde_json.workspace = true

sqlx.workspace = true

[lib]
doctest = false
