[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pg_schema_cache"
repository.workspace = true
version              = "0.0.0"


[dependencies]
async-std            = { version = "1.12.0" }
serde.workspace      = true
serde_json.workspace = true

sqlx.workspace = true

[lib]
doctest = false
