blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/supabase/postgres_lsp/discussions/categories/ideas
    about: Request a new feature or example.
  - name: Ask a question
    url: https://github.com/supabase/postgres_lsp/discussions/categories/q-a
    about: Ask questions and discuss with other community members.
  - name: Want to work with us?
    url: https://supabase.io/humans.txt
    about: Want to work with us? Get in touch!
