[package]
name = "commands"
version = "0.0.0"
edition = "2021"

[dependencies]
text-size = "1.1.1"
sqlx = { version = "0.7.3", features = [ "runtime-async-std", "tls-rustls", "postgres", "json" ] }
async-std = "1.12.0"
anyhow = "1.0.62"

[dev-dependencies]

[lib]
doctest = false

[features]
