[package]
name = "sql_parser"
version = "0.0.0"
edition = "2021"

[dependencies]
petgraph = "0.6.4"
cstree = { version = "0.12.0", features = ["derive"] }
pg_query = "0.8"
regex = "1.9.1"
text-size = "1.1.1"

sql_parser_codegen.workspace = true
pg_query_proto_parser.workspace = true

[dev-dependencies]
insta = "1.31.0"

[lib]
doctest = false

[features]
lazy_cell = []
