[package]
edition = "2021"
name    = "xtask_codegen"
publish = false
version = "0.0.0"

[dependencies]
biome_string_case = { workspace = true }
bpaf              = { workspace = true, features = ["derive"] }
xtask             = { path = '../', version = "0.0" }
