[package]
name = "schema_cache"
version = "0.0.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.3", features = [ "runtime-async-std", "tls-rustls", "postgres", "json" ] }
async-std = { version = "1.12.0" }

[lib]
doctest = false
