[package]
name = "pg_workspace_new"
version = "0.0.0"
edition = "2021"

[dependencies]
text-size.workspace = true
dashmap = "5.5.3"
sqlx = { version = "0.7.3", features = [ "runtime-async-std", "tls-rustls", "postgres", "json" ] }
serde                    = { workspace = true, features = ["derive"] }
serde_json               = { workspace = true, features = ["raw_value"] }

pg_fs.workspace =  true
pg_diagnostics        = { workspace = true }
pg_configuration        = { workspace = true }
pg_console        = { workspace = true }

[dev-dependencies]

[lib]
doctest = false

[features]
