[package]
name = "pg_workspace_new"
version = "0.0.0"
edition = "2021"

[dependencies]
text-size = "1.1.1"
dashmap = "5.5.3"
sqlx = { version = "0.7.3", features = [ "runtime-async-std", "tls-rustls", "postgres", "json" ] }

pg_fs.workspace =  true

[dev-dependencies]

[lib]
doctest = false

[features]
