[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pg_typecheck"
repository.workspace = true
version              = "0.0.0"


[dependencies]
pg_base_db.workspace      = true
pg_query_ext.workspace    = true
pg_schema_cache.workspace = true
pg_syntax.workspace       = true
text-size.workspace       = true

sqlx.workspace = true

async-std = "1.12.0"


[dev-dependencies]

[lib]
doctest = false

[features]
