[package]
name = "pg_typecheck"
version = "0.0.0"
edition = "2021"

[dependencies]
pg_base_db.workspace = true
pg_schema_cache.workspace = true
pg_syntax.workspace = true
pg_query_ext.workspace = true
text-size.workspace = true

sqlx.workspace = true

async-std = "1.12.0"


[dev-dependencies]

[lib]
doctest = false

[features]
