[package]
name = "pg_type_resolver"
version = "0.0.0"
edition = "2021"

[dependencies]
pg_query_ext.workspace = true
pg_schema_cache.workspace = true

[dev-dependencies]

[lib]
doctest = false

[features]
