[package]
name = "pg_query_ext"
version = "0.0.0"
edition = "2021"

[dependencies]
pg_query = "0.8"
petgraph = "0.6.4"

pg_query_ext_codegen.workspace = true
pg_lexer.workspace = true

[lib]
doctest = false
