[package]
name = "base_db"
version = "0.0.0"
edition = "2021"

[dependencies]
text-size = "1.1.1"
parser.workspace = true
line_index.workspace = true
tree-sitter.workspace = true
tree_sitter_sql.workspace = true
tracing.workspace = true

[dev-dependencies]

[lib]
doctest = false

[features]
