[package]
name = "pg_workspace"
version = "0.0.0"
edition = "2021"

[dependencies]
text-size = "1.1.1"
dashmap = "5.5.3"
async-std = "1.12.0"
sqlx = { version = "0.7.3", features = [ "runtime-async-std", "tls-rustls", "postgres", "json" ] }

pg_base_db.workspace =  true
pg_fs.workspace =  true
pg_query_ext.workspace =  true
pg_lint.workspace =  true
pg_syntax.workspace =  true
pg_hover.workspace =  true
pg_typecheck.workspace = true
pg_schema_cache.workspace = true

tree-sitter.workspace = true
tree_sitter_sql.workspace = true

[dev-dependencies]

[lib]
doctest = false

[features]
