[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cstree = { version = "0.12.0", features = ["derive"] }
pg_query = "0.7"
logos = "0.13.0"
triomphe = "0.1.8"
