name: CI

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: --deny warnings

jobs:
  ci:
    name: CI
    timeout-minutes: 10
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run test migrations
        run: psql -f test-db/seed.sql postgresql://postgres:postgres@localhost:5432/postgres

      - name: 📦 Build
        id: build
        run: cargo build

      - name: ⚡️ Check
        id: check
        run: cargo check

      - name: 🦺 Test
        id: test
        run: cargo test
