name: Setup Monorepo
description: Prepare and install everything for the monorepo

inputs:
  github-token:
    description: The GitHub token

  toolchain:
    description: Toolchain name to use
    default: nightly

runs:
  using: composite
  steps:
    - name: 🏗 Setup Toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}

    - name: 🔒 Cache
      uses: swatinem/rust-cache@v2
