name: Setup Monorepo
description: Prepare and install everything for the monorepo

inputs:
  github-token:
    description: The GitHub token

  toolchain:
    description: Toolchain name to use
    default: nightly

runs:
  using: composite
  steps:
    - name: 🏗 Setup Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
